# Generated by Django 6.0.3 on 2026-03-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_user_latitude_user_longitude_vehicle_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos/'),
        ),
    ]
